apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-dta
  sources:
  - repoURL: https://github.com/mojtabaimani/sodeko-platform-services.git
    path: tools/sealed-secrets
    targetRevision: HEAD
    helm:
      releaseName: sealed-secrets
      valueFiles:
        - ../../app-values/sealed-secrets/sealed-secrets-values-dta.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "true"
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
