apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dta
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: project-dta
  source:
    path: ./app-of-apps/dta
    repoURL: https://github.com/mojtabaimani/sodeko-platform-services.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
