apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-prd
  sources:
  - repoURL: https://github.com/mojtabaimani/sodeko-platform-services.git
    path: tools/kube-prometheus-stack
    targetRevision: HEAD
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
        - ../../app-values/prometheus/prometheus-values-prd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "true"
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
